import Head from "next/head";
import SearchFilter from "@/Components/SearchFilter";
import CountryCard from "@/Components/CountryCard";
import { useContext, useEffect, useState } from "react";
import axios from "axios";
import Loading from "@/Components/Loading";
import { ThemeContext } from "./_app";

export default function Home() {
  const theme = useContext(ThemeContext);

  const [data, setData] = useState([]);
  const [searchedCountry, setSearchedCountry] = useState("");
  const [region, setRegion] = useState("");
  // const [code, setCode] = useState("UKR");
  const [isLoading, setLoading] = useState(false);

  //
  useEffect(() => {
    async function fetchCountries() {
      setLoading(true);

      if (searchedCountry !== "") {
        const response = await axios.get(
          `https://restcountries.com/v3.1/name/${searchedCountry}`
        );
        const countriesData = await response.data;
        setData(countriesData);
      } else if (region === "") {
        const response = await axios.get(`https://restcountries.com/v3.1/all`);
        const countriesData = await response.data;
        setData(countriesData);
      } else if (region !== "") {
        const response = await axios.get(
          `https://restcountries.com/v3.1/region/${region}`
        );
        const countriesData = await response.data;
        setData(countriesData);
      }

      setLoading(false);
    }

    fetchCountries();
  }, [searchedCountry, region]);

  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`${
          theme
            ? "bg-vdark-blue-dam text-white"
            : "bg-white text-vdark-blue-lgm"
        }`}
      >
        <SearchFilter
          country={searchedCountry}
          setCountry={setSearchedCountry}
          region={region}
          setRegion={setRegion}
        />

        <div className="w-full h-full">
          {isLoading ? (
            <Loading />
          ) : (
            <div>
              {data && (
                <div className="relative h-full grid grid-cols-4 gap-16 1bp:gap-5 2bp:grid-cols-3 3bp:grid-cols-2 mx-auto 5bp:grid-cols-1 justify-items-center">
                  {data?.map((country: any) => (
                    <CountryCard
                      key={country.name.common}
                      flag_image={country.flags.svg}
                      name={country.name.common}
                      population={country.population}
                      region={country.region}
                      capital={country.capital}
                    />
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
